# uncompyle6 version 3.2.3
# Python bytecode 3.6 (3379)
# Decompiled from: Python 2.7.5 (default, Jul 13 2018, 13:06:57) 
# [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
# Embedded file name: ./api/enum/performance_enum.py
# Compiled at: 2018-08-23 19:33:14
# Size of source mod 2**32: 12817 bytes
from enum import Enum
NAME_ENUM = {'HOST CPU UTILIZATION (%)':1, 
 'LOG FILE SYNC':2, 
 'LOG FILE PARALLEL WRITE':3, 
 'DB FILE PARALLEL WRITE':4, 
 'DB FILE SEQUENTIAL READ':5, 
 'DB FILE SCATTERED READ':6, 
 'DIRECT PATH READ':7, 
 'DIRECT PATH READ TEMP':8, 
 'HARD PARSE COUNT PER SEC':9, 
 'TOTAL PARSE COUNT PER SEC':10, 
 'PARSE FAILURE COUNT PER SEC':11, 
 'PHYSICAL WRITE IO REQUESTS PER SEC':12, 
 'PHYSICAL WRITE TOTAL BYTES PER SEC':13, 
 'PHYSICAL READ IO REQUESTS PER SEC':14, 
 'PHYSICAL READ TOTAL BYTES PER SEC':15, 
 'REDO GENERATED PER SEC':16, 
 'LOGICAL READS PER SEC':17, 
 'EXECUTIONS PER SEC':18, 
 'LOGONS PER SEC':19, 
 'SESSION COUNT':20, 
 'USER COMMITS PER SEC':21, 
 'USER ROLLBACKS PER SEC':22, 
 'USER CALLS PER SEC':23, 
 'GC CR BLOCK RECEIVED PER SECOND':24, 
 'GC CURRENT BLOCK RECEIVED PER SECOND':25, 
 'GLOBAL CACHE AVERAGE CR GET TIME':26, 
 'GLOBAL CACHE AVERAGE CURRENT GET TIME':27, 
 'GLOBAL CACHE BLOCKS LOST':28, 
 'APPLY LAG':29, 
 'TRANSPORT LAG':30, 
 'SCN GAP PER MINUTE':31, 
 'THREAD_CONNECTED':32, 
 'QUERIES':33, 
 'QUESTIONS':33, 
 'COM_DELETE':34, 
 'COM_INSERT':35, 
 'COM_SELECT':36, 
 'COM_UPDATE':37, 
 'BYTES_RECEIVED':38, 
 'BYTES_SENT':39, 
 'KEY BUFFER':40, 
 'QUERY CACHE':41, 
 'THREAD CACHE':42, 
 'TABLE CACHE':43, 
 'INNODB BUFFER POOL READ':45, 
 'SELECT_FULL_JOIN':46, 
 'SELECT_FULL_RANGE_JOIN':47, 
 'SELECT_RANGE':48, 
 'SELECT_RANGE_CHECK':49, 
 'SELECT_SCAN':50, 
 'SORT_MERGE_PASSES':51, 
 'SORT_SCAN':52, 
 'SORT_RANGE':53, 
 'SORT_ROWS':54, 
 'CREATED_TMP_DISK_TABLES':55, 
 'CREATED_TMP_FILES':56, 
 'CREATED_TMP_TABLES':57, 
 'INNODB_DATA_WRITES':58, 
 'INNODB_LOG_WRITES':59, 
 'INNODB_OS_LOG_WRITTEN':60, 
 'INNODB_ROWS_READ':61, 
 'INNODB_ROWS_INSERTED':62, 
 'INNODB_ROWS_UPDATED':63, 
 'INNODB_ROWS_DELETED':64, 
 'BATCH REQUESTS/SEC':65, 
 'SQL COMPILATIONS/SEC':66, 
 'SQL RE-COMPILATIONS/SEC':67, 
 'LAZY WRITES/SEC':68, 
 'PAGE LIFE EXPECTANCY':69, 
 'CONNECTION MEMORY (KB)':70, 
 'MEMORY GRANTS PENDING':71, 
 'SQL CACHE MEMORY (KB)':72, 
 'TARGET SERVER MEMORY (KB)':73, 
 'TOTAL SERVER MEMORY (KB)':74, 
 'FULL SCANS/SEC':75, 
 'FORWARDED RECORDS/SEC':76, 
 'MIXED PAGE ALLOCATIONS/SEC':77, 
 'PAGE SPLITS/SEC':78, 
 'TABLE LOCK ESCALATIONS/SEC':79, 
 'WORKFILES CREATED/SEC':80, 
 'WORKTABLES CREATED/SEC':81, 
 'LOGINS/SEC':82, 
 'LOGOUTS/SEC':83, 
 'USER CONNECTIONS':84, 
 'PROCESSES BLOCKED':85, 
 'ACTIVE TEMP TABLES':86, 
 'TEMP TABLES CREATION RATE':87, 
 'TEMP TABLES FOR DESTRUCTION':88, 
 'LATCH WAITS/SEC':89, 
 'AVERAGE LATCH WAIT TIME (MS)':90, 
 'ACTIVE TRANSACTIONS':91, 
 'LOG FLUSHES/SEC':92, 
 'TRANSACTIONS/SEC':93, 
 'LOG FLUSHES/SEC':94, 
 'LOCK REQUESTS/SEC':95, 
 'NUMBER OF DEADLOCKS/SEC':96, 
 'LOCK WAITS/SEC':97, 
 'LOCK WAIT TIME (MS)':98, 
 'LOCK TIMEOUTS (TIMEOUT > 0)/SEC':99, 
 'ACTIVE_SORTS':100, 
 'TOTAL_SORTS':101, 
 'SORT_OVERFLOWS':102, 
 'APPLS_CUR_CONS':103, 
 'APPLS_IN_DB2':104, 
 'TOTAL_CONS':105, 
 'NUM_ASSOC_AGENTS':106, 
 'COMMIT_SQL_STMTS':107, 
 'ROLLBACK_SQL_STMTS':108, 
 'DYNAMIC_SQL_STMTS':109, 
 'STATIC_SQL_STMTS':110, 
 'FAILED_SQL_STMTS':111, 
 'SELECT_SQL_STMTS':112, 
 'UID_SQL_STMTS':113, 
 'DDL_SQL_STMTS':114, 
 'DIRECT_READS':115, 
 'DIRECT_WRITES':116, 
 'LOCKS_WAITING':117, 
 'LOCKS_HELD':118, 
 'LOCK_WAITS':119, 
 'LOG_READS':120, 
 'LOG_WRITES':121, 
 'POOL_DATA_L_READS':122, 
 'POOL_TEMP_DATA_L_READS':123, 
 'POOL_INDEX_L_READS':124, 
 'POOL_TEMP_INDEX_L_READS':125, 
 'POOL_XDA_L_READS':126, 
 'POOL_TEMP_XDA_L_READS':127, 
 'POOL_DATA_P_READS':128, 
 'POOL_TEMP_DATA_P_READS':129, 
 'POOL_INDEX_P_READS':130, 
 'POOL_TEMP_INDEX_P_READS':131, 
 'POOL_XDA_P_READS':132, 
 'POOL_TEMP_XDA_P_READS':133, 
 'POOL_DATA_WRITES':134, 
 'POOL_INDEX_WRITES':135, 
 'POOL_XDA_WRITES':136, 
 'ROWS_DELETED':137, 
 'ROWS_INSERTED':138, 
 'ROWS_UPDATED':139, 
 'ROWS_SELECTED':140, 
 'ROWS_READ':141, 
 'LOCK TIMEOUTS/SEC':142, 
 'CONNECTIONS':143, 
 'INNODB_BUFFER_POOL_READ_REQUESTS':144, 
 'INNODB_DATA_READS':145}
VALUE_ENUM = {'1':'HOST CPU UTILIZATION (%)', 
 '2':'LOG FILE SYNC', 
 '3':'LOG FILE PARALLEL WRITE', 
 '4':'DB FILE PARALLEL WRITE', 
 '5':'DB FILE SEQUENTIAL READ', 
 '6':'DB FILE SCATTERED READ', 
 '7':'DIRECT PATH READ', 
 '8':'DIRECT PATH READ TEMP', 
 '9':'HARD PARSE COUNT PER SEC', 
 '10':'TOTAL PARSE COUNT PER SEC', 
 '11':'PARSE FAILURE COUNT PER SEC', 
 '12':'PHYSICAL WRITE IO REQUESTS PER SEC', 
 '13':'PHYSICAL WRITE TOTAL BYTES PER SEC', 
 '14':'PHYSICAL READ IO REQUESTS PER SEC', 
 '15':'PHYSICAL READ TOTAL BYTES PER SEC', 
 '16':'REDO GENERATED PER SEC', 
 '17':'LOGICAL READS PER SEC', 
 '18':'EXECUTIONS PER SEC', 
 '19':'LOGONS PER SEC', 
 '20':'SESSION COUNT', 
 '21':'USER COMMITS PER SEC', 
 '22':'USER ROLLBACKS PER SEC', 
 '23':'USER CALLS PER SEC', 
 '24':'GC CR BLOCK RECEIVED PER SECOND', 
 '25':'GC CURRENT BLOCK RECEIVED PER SECOND', 
 '26':'GLOBAL CACHE AVERAGE CR GET TIME', 
 '27':'GLOBAL CACHE AVERAGE CURRENT GET TIME', 
 '28':'GLOBAL CACHE BLOCKS LOST', 
 '29':'APPLY LAG', 
 '30':'TRANSPORT LAG', 
 '31':'SCN GAP PER MINUTE', 
 '32':'THREAD_CONNECTED', 
 '33':'QUERIES', 
 '34':'COM_DELETE', 
 '35':'COM_INSERT', 
 '36':'COM_SELECT', 
 '37':'COM_UPDATE', 
 '38':'BYTES_RECEIVED', 
 '39':'BYTES_SENT', 
 '40':'KEY BUFFER', 
 '41':'QUERY CACHE', 
 '42':'THREAD CACHE', 
 '43':'TABLE CACHE', 
 '45':'INNODB BUFFER POOL READ', 
 '46':'SELECT_FULL_JOIN', 
 '47':'SELECT_FULL_RANGE_JOIN', 
 '48':'SELECT_RANGE', 
 '49':'SELECT_RANGE_CHECK', 
 '50':'SELECT_SCAN', 
 '51':'SORT_MERGE_PASSES', 
 '52':'SORT_SCAN', 
 '53':'SORT_RANGE', 
 '54':'SORT_ROWS', 
 '55':'CREATED_TMP_DISK_TABLES', 
 '56':'CREATED_TMP_FILES', 
 '57':'CREATED_TMP_TABLES', 
 '58':'INNODB_DATA_WRITES', 
 '59':'INNODB_LOG_WRITES', 
 '60':'INNODB_OS_LOG_WRITTEN', 
 '61':'INNODB_ROWS_READ', 
 '62':'INNODB_ROWS_INSERTED', 
 '63':'INNODB_ROWS_UPDATED', 
 '64':'INNODB_ROWS_DELETED', 
 '65':'BATCH REQUESTS/SEC', 
 '66':'SQL COMPILATIONS/SEC', 
 '67':'SQL RE-COMPILATIONS/SEC', 
 '68':'LAZY WRITES/SEC', 
 '69':'PAGE LIFE EXPECTANCY', 
 '70':'CONNECTION MEMORY (KB)', 
 '71':'MEMORY GRANTS PENDING', 
 '72':'SQL CACHE MEMORY (KB)', 
 '73':'TARGET SERVER MEMORY (KB)', 
 '74':'TOTAL SERVER MEMORY (KB)', 
 '75':'FULL SCANS/SEC', 
 '76':'FORWARDED RECORDS/SEC', 
 '77':'MIXED PAGE ALLOCATIONS/SEC', 
 '78':'PAGE SPLITS/SEC', 
 '79':'TABLE LOCK ESCALATIONS/SEC', 
 '80':'WORKFILES CREATED/SEC', 
 '81':'WORKTABLES CREATED/SEC', 
 '82':'LOGINS/SEC', 
 '83':'LOGOUTS/SEC', 
 '84':'USER CONNECTIONS', 
 '85':'PROCESSES BLOCKED', 
 '86':'ACTIVE TEMP TABLES', 
 '87':'TEMP TABLES CREATION RATE', 
 '88':'TEMP TABLES FOR DESTRUCTION', 
 '89':'LATCH WAITS/SEC', 
 '90':'AVERAGE LATCH WAIT TIME (MS)', 
 '91':'ACTIVE TRANSACTIONS', 
 '92':'LOG FLUSHES/SEC', 
 '93':'TRANSACTIONS/SEC', 
 '94':'LOG FLUSHES/SEC', 
 '95':'LOCK REQUESTS/SEC', 
 '96':'NUMBER OF DEADLOCKS/SEC', 
 '97':'LOCK WAITS/SEC', 
 '98':'LOCK WAIT TIME (MS)', 
 '99':'LOCK TIMEOUTS (TIMEOUT > 0)/SEC', 
 '100':'ACTIVE_SORTS', 
 '101':'TOTAL_SORTS', 
 '102':'SORT_OVERFLOWS', 
 '103':'APPLS_CUR_CONS', 
 '104':'APPLS_IN_DB2', 
 '105':'TOTAL_CONS', 
 '106':'NUM_ASSOC_AGENTS', 
 '107':'COMMIT_SQL_STMTS', 
 '108':'ROLLBACK_SQL_STMTS', 
 '109':'DYNAMIC_SQL_STMTS', 
 '110':'STATIC_SQL_STMTS', 
 '111':'FAILED_SQL_STMTS', 
 '112':'SELECT_SQL_STMTS', 
 '113':'UID_SQL_STMTS', 
 '114':'DDL_SQL_STMTS', 
 '115':'DIRECT_READS', 
 '116':'DIRECT_WRITES', 
 '117':'LOCKS_WAITING', 
 '118':'LOCKS_HELD', 
 '119':'LOCK_WAITS', 
 '120':'LOG_READS', 
 '121':'LOG_WRITES', 
 '122':'POOL_DATA_L_READS', 
 '123':'POOL_TEMP_DATA_L_READS', 
 '124':'POOL_INDEX_L_READS', 
 '125':'POOL_TEMP_INDEX_L_READS', 
 '126':'POOL_XDA_L_READS', 
 '127':'POOL_TEMP_XDA_L_READS', 
 '128':'POOL_DATA_P_READS', 
 '129':'POOL_TEMP_DATA_P_READS', 
 '130':'POOL_INDEX_P_READS', 
 '131':'POOL_TEMP_INDEX_P_READS', 
 '132':'POOL_XDA_P_READS', 
 '133':'POOL_TEMP_XDA_P_READS', 
 '134':'POOL_DATA_WRITES', 
 '135':'POOL_INDEX_WRITES', 
 '136':'POOL_XDA_WRITES', 
 '137':'ROWS_DELETED', 
 '138':'ROWS_INSERTED', 
 '139':'ROWS_UPDATED', 
 '140':'ROWS_SELECTED', 
 '141':'ROWS_READ', 
 '142':'LOCK TIMEOUTS/SEC', 
 '143':'CONNECTIONS', 
 '144':'INNODB_BUFFER_POOL_READ_REQUESTS', 
 '145':'INNODB_DATA_READS'}

class OraclePerformanceType(Enum):
    CPU = '1'
    WAIT = '2,3,4,5,6,7,8'
    PARSE = '9,10,11'
    IO = '12,13,14,15,16,17'
    OTHER = '18,19,20,21,22,23'
    RAC = '24,25,26,27,28'
    DG = '29,30'
    SCN = '31'

    def __str__(self):
        switcher = {'CPU':'CPU (%)', 
         'PARSE':'', 
         'IO':'IO ', 
         'WAIT':'IO ()', 
         'OTHER':'', 
         'RAC':'RAC ()', 
         'DG':'()', 
         'SCN':'SCN ()'}
        return switcher.get(self.name, '')


class MySQLPerformanceType(Enum):
    QUERY = '32,33,34,35,36,37,38'
    NETWORK = '38,39'
    CACHE = '40,41,42,43,44,45'
    SELECT = '46,47,48,49,50'
    SORT = '51,52,53,54'
    TMP = '55,56,57'
    INNODBW = '58,59,60'
    INNODBR = '61,62,63,64'

    def __str__(self):
        switcher = {'QUERY':'QPS', 
         'NETWORK':'', 
         'CACHE':'', 
         'SELECT':'', 
         'SORT':'', 
         'TMP':'', 
         'INNODBW':'Innodb ', 
         'INNODBR':'Innodb '}
        return switcher.get(self.name, '')


class SQLServerPerformanceType(Enum):
    SQL_STATISTICS = '65,66,67'
    BUFFER_MANAGER = '68,69'
    MEMORY_MANAGER = '70,71,72,73,74'
    ACCESS_METHODS = '75,76,77,78,79,80,81'
    GENERAL_STATISTICS = '82,83,84,85,86,87,88'
    LATCHES = '89,90'
    DATABASES = '91,92,93'
    LOCKS = '94,95,96,97,98,99'

    def __str__(self):
        switcher = {'SQL_STATISTICS':'SQL', 
         'BUFFER_MANAGER':'', 
         'MEMORY_MANAGER':'', 
         'ACCESS_METHODS':'', 
         'GENERAL_STATISTICS':'', 
         'LATCHES':'LATCHES', 
         'DATABASES':'', 
         'LOCKS':''}
        return switcher.get(self.name, '')


class PostgresPerformanceType(Enum):
    BACKENDS = "'NUMBACKENDS'"
    TRANSACTION = "'XACT_COMMIT','XACT_ROLLBACK'"
    RATIO = "'BLKS_READ', 'BLKS_HIT'"
    TUPLE = "'TUP_RETURNED', 'TUP_FETCHED', 'TUP_INSERTED', 'TUP_UPDATED', 'TUP_DELETED'"

    def __str__(self):
        switcher = {'BACKENDS':'', 
         'TRANSACTION':'', 
         'RATIO':'IO ', 
         'TUPLE':'Tuple '}
        return switcher.get(self.name, '')


class DB2PerformanceType(Enum):
    SORT = '100,101,102'
    APP = '103,104,105,106'
    STMT = '107,108,109,110,111,112,113,114'
    DIRECT = '115,116'
    LOCK = '117,118,119'
    LOG = '120,121'
    POOLREAD = '122,123,124,1245,126,127,128,129,130,131,132,133'
    POOLWRITE = '134,135,136'
    ROW = '137,138,139,140,141'

    def __str__(self):
        switcher = {'SORT':'', 
         'APP':'', 
         'STMT':'SQL', 
         'DIRECT':'IO', 
         'LOCK':'', 
         'LOG':'LOG', 
         'POOLREAD':'', 
         'POOLWRITE':'', 
         'ROW':''}
        return switcher.get(self.name, '')
# okay decompiling ./restful/hawkeye/api/enum/performance_enum.pyc
